kind: Service
apiVersion: v1
metadata:
  labels:
    name: email-api
  name: email-api
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: httpadmin
      port: 8081
      targetPort: 8081
  selector:
    name: email-api